#count occurences of A,T,G,C
dna = 'TCTTGTACGCCTAAAAGACTCCCGGGGTGAGGGCCGAGCCTCCTAGGGCACCCGTAGTGTAGGGACTGTACAATTTACACGTATCTGGGTGGGCTCAGCAATTCCACTGCTCATGAGCGCGGCCGGACCTATGTTGAAATAAGTATTGGCCATCGAATACGCATATGAGCTTCGGCTCACGCACTAGGTGCTTTTGGTGCTCAATCCGAGAACACAAAAAGTTGAAGGTTACGTATAATCCCGGTCTTCCTCAATTTCTGGTCACCCAGTGCTGATAGTCGACAGGCTCTACCGTAATATGAAAGTAGTTGCTCGGCTCTGCAACGGGCGGGAACCGTGGCTGATTATTTTAAGTGTATTATAAGCCACTGGAGATATAGTGGTATCCCCCGGAGGTAAATCCCAATCACAGTATGCCCTTAGTGCACTTCCGCTGCGAACCTTAGCTAGATAGTTCCCCGAGACCAACAGTCTGGTCGCCATTCGCGTGTGAAGTTGCAGAAAGTTGGCACAGCCCTGCCCAGAACAATTCATTTATGACATGAGGCGCCCAGTCTTGGCATAGTGAAACCTGTGGTAAGTTCACGGTGTTAGGGCAAGCATCAATAGCACTCGGGACACCCTCATAACTTCACCGAATTAAAACAGGCGGAGCGGCATTGATGCTACCCACGCCTTCTTTTAAGCATCGCTGAATCAAAGGACCGCTCAACACGGGTAAGCCTTATATACAGTACGTACTCACCTTATAACCCAGATCTAACAGCAGGCCCGCTAGATATCTGCCATCTCTCTCCAGGGAAATAACACTTAGCTTTTGTAGTATTGCTGCGGTCACAGTATGGGACAAAACAGACGG'
a,t,g,c = (0,0,0,0)

for base in dna:
  if base=='A':
    a+= 1
  elif base=='G':
    g+= 1
  elif base=='C':
    c+= 1
  elif base=='T':
    t+= 1

print("{0} {1} {2} {3}".format(a,c,g,t))